apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvd
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/jenkins
    path: /var/run
