apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-29T01:55:48Z"
  generation: 9
  labels:
    app: jenkins
    chart: jenkins-4.1.2
    heritage: Tiller
    release: whopping-ibis
  name: whopping-ibis-jenkins
  namespace: default
  resourceVersion: "217205"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/whopping-ibis-jenkins
  uid: 78364a10-423a-11ea-a3bc-62be43561ceb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
      release: whopping-ibis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        chart: jenkins-4.1.2
        heritage: Tiller
        release: whopping-ibis
    spec:
      containers:
      - env:
        - name: JENKINS_USERNAME
          value: user
        - name: JENKINS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: jenkins-password
              name: whopping-ibis-jenkins
        - name: JENKINS_HOME
          value: /opt/bitnami/jenkins/jenkins_home
        - name: DISABLE_JENKINS_INITIALIZATION
          value: "no"
        image: marketplace.azurecr.io/bitnami/jenkins:2.204.1-debian-9-r2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/jenkins
          name: jenkins-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: whopping-ibis-jenkins
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-29T02:10:53Z"
    lastUpdateTime: "2020-01-29T02:10:53Z"
    message: ReplicaSet "whopping-ibis-jenkins-6c58d87bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-29T03:27:43Z"
    lastUpdateTime: "2020-01-29T03:27:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
